# Generated by Django 5.0 on 2023-12-12 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Cidade')),
            ],
        ),
        migrations.CreateModel(
            name='DadosAgendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.TimeField(verbose_name='Horário de Início')),
                ('termino', models.TimeField(verbose_name='Horário de Término')),
                ('data', models.DateField(verbose_name='Data do Agendamento')),
                ('duracao', models.PositiveSmallIntegerField(verbose_name='Duração do Agendamento')),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Estado')),
                ('sigla', models.CharField(max_length=5, verbose_name='Sigla da UF')),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=200, verbose_name='Endereço')),
                ('bairro', models.CharField(max_length=100, verbose_name='Nome do Bairro')),
                ('numero', models.CharField(max_length=20, verbose_name='Número do Local')),
                ('complemento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.cidade', verbose_name='Cidade do Endereço')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=250, verbose_name='Nome da Empresa')),
                ('slug_empresa', models.SlugField(verbose_name='Slug da Empresa')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone da Empresa')),
                ('tipo_negocio', models.CharField(choices=[(' ', 'Escolha o tipo do negócio'), ('ESPORTES', 'Esportes'), ('SAÚDE', 'Saúde'), ('OUTRO', 'Outro')], default=' ', max_length=8, verbose_name='Tipo do Negócio')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.endereco', verbose_name='Endereço da Empresa')),
            ],
            options={
                'db_table': 'empresas_empresa',
            },
        ),
        migrations.AddField(
            model_name='cidade',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.estado', verbose_name='Estado da Cidade'),
        ),
    ]
