# Generated by Django 5.0 on 2023-12-12 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicoAgendavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_servico', models.CharField(max_length=200, verbose_name='Servico Ofertado')),
                ('custo', models.FloatField(verbose_name='Preço do Serviço')),
                ('empresa_possuinte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.empresa', verbose_name='Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custo_agendamento', models.FloatField(verbose_name='Custo do Agendamento', blank=True)),
                ('servico_agendado', models.ManyToManyField(to='empresa.servicoagendavel', verbose_name='Servico Agendado')),
            ],
        ),
    ]
