# Generated by Django 5.0 on 2023-12-12 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
        ('empresa', '0002_alter_agendamento_custo_agendamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='informacoes_padroes',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='components.dadosagendamento', verbose_name='Dados do Agendamento'),
            preserve_default=False,
        ),
    ]
